development:
  provider: <%= ENV["EMAIL_SERVICE_PROVIDER"] || "PSEUDO" %>
  email_address_override:

test:
  provider: <%= ENV["EMAIL_SERVICE_PROVIDER"] || "PSEUDO" %>
  email_address_override:

production:
  provider: <%= ENV["EMAIL_SERVICE_PROVIDER"] || "NOTIFY" %>
  email_address_override:
